# Generated by Django 5.1.4 on 2025-04-21 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, null=True, verbose_name="商品名"),
                ),
                (
                    "category_id",
                    models.IntegerField(
                        choices=[(1, "书本"), (2, "手机"), (3, "衣服"), (4, "其他")],
                        null=True,
                        verbose_name="商品分类id",
                    ),
                ),
                ("cover_list", models.TextField(null=True, verbose_name="商品封面列表")),
                ("detail", models.TextField(null=True, verbose_name="商品简介")),
                (
                    "inventory",
                    models.IntegerField(default=1, null=True, verbose_name="库存"),
                ),
                (
                    "is_bargain",
                    models.BooleanField(
                        default=False, null=True, verbose_name="是否支持砍价"
                    ),
                ),
                ("old_level", models.IntegerField(null=True, verbose_name="新旧程度")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="价格"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["-create_at"],
            },
        ),
    ]
